### ISSUE TITLE
HtmlDjango is not working 

### ISSUE THREAD

**Issue by Johan-Palacios** [kabouzeid/nvim-lspinstall#142]
OS: WLS (Ubuntu)
Editor: Nvim 0.5

Hi, I installed with `:LspInstall html` the html server, but if I want to work with the autocomplete it not works

![image](https://user-images.githubusercontent.com/77251405/129455635-a868d70e-51dd-4121-98c7-338e123f126c.png)

**Comment by gusvianadev** [comment]
I have a similar issue. I get the message `Client 1 quit with exit code 1 and signal 0` when opening html, css or json files
I think it has something to do with the vscode servers

**Comment by Johan-Palacios** [comment]
Its probably that is a problem with the servers, because Html LSP is enabled, but it not shows the autocomplete

**Comment by chris-av** [comment]
OS: Darwin/MacbookPro
Nvim 0.5

> I have a similar issue. I get the message `Client 1 quit with exit code 1 and signal 0` when opening html, css or json files I think it has something to do with the vscode servers

I get the same exact error, trying to figure this out myself. When I try look at the lsp logs it looks something like this: 

```
[ ERROR ] 2021-09-30T21:18:28-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"node"	"stderr"	"/Users/chrisvalenzuela/.local/share/nvim/lspinstall/css/vscode-css/css-language-features/server/dist/node/cssServerMain.js:1\n(()=>{\"use strict\";var e={7254:(e,t,n)=>{var r;n.r(t),n.d(t,{ClientCapabilities:()=>tn,CodeAction:()=>dn.CodeAction,CodeActionContext:()=>dn.CodeActionContext,CodeActionKind:()=>dn.CodeActionKind,Color:()=>dn.Color,ColorInformation:()=>dn.ColorInformation,ColorPresentation:()=>dn.ColorPresentation,Command:()=>dn.Command,CompletionItem:()=>dn.CompletionItem,CompletionItemKind:()=>dn.CompletionItemKind,CompletionItemTag:()=>dn.CompletionItemTag,CompletionList:()=>dn.CompletionList,Diagnostic:()=>dn.Diagnostic,DiagnosticSeverity:()=>dn.DiagnosticSeverity,DocumentHighlight:()=>dn.DocumentHighlight,DocumentHighlightKind:()=>dn.DocumentHighlightKind,DocumentLink:()=>dn.DocumentLink,DocumentSymbol:()=>dn.DocumentSymbol,FileType:()=>nn,FoldingRange:()=>dn.FoldingRange,FoldingRangeKind:()=>dn.FoldingRangeKind,Hover:()=>dn.Hover,InsertTextFormat:()=>dn.InsertTextFormat,Location:()=>dn.Location,\n\nSyntaxError: Unexpected token '.'\n    at Module._compile (internal/modules/cjs/loader.js:892:18)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n    at Module.load (internal/modules/cjs/loader.js:812:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)\n    at internal/main/run_main_module.js:17:11\n"
```

First error at the top is pointing me here `$HOME/.local/share/nvim/lspinstall/css/vscode-css/css-language-features/server/dist/node/cssServerMain.js`: 

And it says `Unexpected token '.'\n`. So would this be an issue with the vs-code repo? 

When I run `:LspInstall css` I don't get any errors. Only when I open the files.
